[tool.pylint]
# Pylint configuration
disable = [
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116",  # missing-function-docstring
    "R0903", # too-few-public-methods
]
max-line-length = 100
output-format = "text"

[tool.mypy]
# Mypy configuration
files = "app"  # Specify the directory to check
ignore_missing_imports = true
strict = true  # Enable all optional checks
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
disable_error_code = ["valid-type"]  # Ignore "Invalid type comment or annotation"
