name: Pylint Scores

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: app
          python-version: ${{ matrix.python-version }}